"""create_tables

Revision ID: 02ea46109035
Revises:
Create Date: 2023-11-19 21:40:54.142087

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = '02ea46109035'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=10), nullable=False),
    sa.Column('seller', sa.Boolean(), nullable=False),
    sa.Column('account_balance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchased', sa.Boolean(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('origin_city', sa.String(length=20), nullable=False),
    sa.Column('origin_state', sa.String(length=20), nullable=False),
    sa.Column('available', sa.Integer(), nullable=False),
    sa.Column('preview_image', sa.String(length=255), nullable=False),
    sa.Column('product_image1', sa.String(length=255), nullable=False),
    sa.Column('product_image2', sa.String(length=255), nullable=False),
    sa.Column('product_image3', sa.String(length=255), nullable=False),
    sa.Column('product_image4', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['seller'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('headline', sa.String(length=255), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('review_image', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wishlists',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('member_id', 'product_id')
    )

    if environment == "production":
        op.execute(f"ALTER TABLE members SET SCHEMA {SCHEMA};
                   ALTER TABLE orders SET SCHEMA {SCHEMA};
                   ALTER TABLE products SET SCHEMA {SCHEMA};
                   ALTER TABLE order_details SET SCHEMA {SCHEMA};
                   ALTER TABLE reviews SET SCHEMA {SCHEMA};
                   ALTER TABLE wishlists SET SCHEMA {SCHEMA};
                   ")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishlists')
    op.drop_table('reviews')
    op.drop_table('order_details')
    op.drop_table('products')
    op.drop_table('orders')
    op.drop_table('members')
    # ### end Alembic commands ###
